name: FedsnCrims
version: 0.0.3
description: The Feds 'n Crims plugin for Pixel Network.
author: Xaaf

main: gq.pixelnetwork.fedsncrims.Main

commands:
    fnc:
        usage: Syntax error! Please enter a valid command!
        description: The base command for all Feds 'n Crims.

permissions:
    fnc.*:
        description: Gives permission for all Feds 'n Crims commands.
        children:
            fnc.base: true
            fnc.debug: true
    fnc.base:
        description: Gives permission for all basic Feds 'n Crims commands.
    fnc.debug:
        description: Gives permission for all debug related commands.
